export const MENUITEM_LIST_REQUEST = 'MENUITEM_LIST_REQUEST';
export const MENUITEM_LIST_SUCCESS = 'MENUITEM_LIST_SUCCESS';
export const MENUITEM_LIST_FAIL = 'MENUITEM_LIST_FAIL';

export const MENUITEM_DETAILS_REQUEST = 'MENUITEM_DETAILS_REQUEST';
export const MENUITEM_DETAILS_SUCCESS = 'MENUITEM_DETAILS_SUCCESS';
export const MENUITEM_DETAILS_FAIL = 'MENUITEM_DETAILS_FAIL';
